### ISSUE TITLE
Next add telegram

### ISSUE THREAD

**Issue by tomoayan** [5ut/DiskCord#1]

**Comment by 04anubhavv** [comment]
Let's wait for @5ut  to comment, but  I don't think telegram can be used cause they don't have static links

**Comment by 5ut** [comment]
I've never looked into telegrams layout personally, but you would need a static link for sure. 

I'll take a look at telegram next chance I get. If someone is interested, just look for how telegram hosts files. If you can find a way to upload file and link them, you should be able to make this work.

You'd be surprised what can  be accessed using some unintended links. 

Thanks for the feedback :)

**Comment by 5ut** [comment]
I looked into telegram, I hate to say but I don't believe that won't be possible. It's an encrypted file that's decrypted client side using something with your session. 

At minimum you would need a way to prompt for a login, and get a session. 

There might be some kind of bugs, or creative work arounds however. Those would need to be really dug for however.

Closing.
